### ISSUE TITLE
Mảng sau khi thêm số 0 không khác gì mảng không thêm bạn ạ 

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#10]
https://github.com/20021423/baitapmangP1-becodeching/blob/9631d56875ee65d92b9123eb6343030ebb896f74/bai2.cpp#L71
<img width="341" alt="image" src="https://user-images.githubusercontent.com/52942703/112867240-e1319b80-90e4-11eb-89e8-e337e95a904e.png">

**Comment by 20021423** [comment]
đề bài là thêm số 0 vào trước số hoàn thiện chứ không số nguyên tố mà bạn.
