### ISSUE TITLE
Chỉ giữ lại 1 số nguyên duy nhất !

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#11]
https://github.com/20021423/baitapmangP1-becodeching/blob/9631d56875ee65d92b9123eb6343030ebb896f74/bai3.cpp#L41

<img width="255" alt="image" src="https://user-images.githubusercontent.com/52942703/112867430-1f2ebf80-90e5-11eb-9bdf-4d30159efcd7.png">

**Comment by 20021423** [comment]
mình sẽ thêm j-- vào đoạn code này
void XoaPhanTuTrungNhau(int a[], int& n)
{
	for (int i = 0; i < n -1; i++)
	{
		for (int j = i + 1; j < n; j++)
		{
			if (a[j] == a[i])
			{
				XoaPhanTu(a, n, j);

			}
		}
	}
}
