### ISSUE TITLE
Function này k được sử dụng 

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#14]
https://github.com/20021423/baitapmangP1-becodeching/blob/d3f95af92198510e779ad012e2a6b0c85d8d2b3b/level2-bai3.cpp#L24

**Comment by 20021423** [comment]
hic, mình làm cứ copy hàm của 5 file với nhau cả 5 file mình làm xong test rồi mà quên chưa save mình sẽ sửa ngay
