### ISSUE TITLE
Tại sao lại không mix hai mảng lại với nhau rồi hẵng sắp xếp. Lúc đó có phải bài toán trở nên đơn giản hơn đúng k ? Viết hàm sort có phải gọn hơn kg ?

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#15]
https://github.com/20021423/baitapmangP1-becodeching/blob/d3f95af92198510e779ad012e2a6b0c85d8d2b3b/level2-bai3.cpp#L84

**Comment by 20021423** [comment]
mình có làm cách đó rồi, đây là cách 2 của mình
