### ISSUE TITLE
Khai báo 1 mảng có 7 phần tử kiểu gì vậy bạn ? Kiểu float nhé

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#2]
https://github.com/20021423/baitapmangP1-becodeching/blob/777380dc9b37955faa49f94827e61359258dbd95/B%C3%A0i%20t%E1%BA%ADp%20l%C3%BD%20thuy%E1%BA%BFt%20m%E1%BA%A3ng%20p1.txt#L7

**Comment by 20021423** [comment]
int a[7] là khai báo 1 mảng có tối đa 7 phần tử cùng kiểu nguyên int
