### ISSUE TITLE
Chắc là sizeof(a) mình nghĩ vậy :>

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#3]
https://github.com/20021423/baitapmangP1-becodeching/blob/777380dc9b37955faa49f94827e61359258dbd95/B%C3%A0i%20t%E1%BA%ADp%20l%C3%BD%20thuy%E1%BA%BFt%20m%E1%BA%A3ng%20p1.txt#L9

**Comment by 20021423** [comment]
sizeof(a) = n * sizeof(<kiểu dữ liệu>)
