### ISSUE TITLE
Số phần tử trong mảng có thể âm không ?

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#4]
https://github.com/20021423/baitapmangP1-becodeching/blob/777380dc9b37955faa49f94827e61359258dbd95/bai1mangP1.cpp#L37

**Comment by 20021423** [comment]
minh se sua lai la:
do
    {
        cout << "Nhap so phan tu cua mang: ";
        cin >> n;
    } while (n <= 0);
