### ISSUE TITLE
Số 0 có thể là số dương k bạn ? 

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#7]
https://github.com/20021423/baitapmangP1-becodeching/blob/777380dc9b37955faa49f94827e61359258dbd95/Bai4mangP1.cpp#L41

![image](https://user-images.githubusercontent.com/52942703/112714840-02409380-8f0f-11eb-8ff9-edc6cf045dce.png)

**Comment by 20021423** [comment]
minh sẽ sửa điều kiện chặt hơn
bool KiemtraHamToanDuong(int a[], int n)
{
    for (int i = 0; i < n; i++)
    {
        if (a[i] <= 0)
        {
            cout << "Mang khong toan duong" << endl;
            return false;
        }
    }
    cout << "Mang toan duong";
    return true;
}
