### ISSUE TITLE
Xoá các số trùng mà sao các số trùng vẫn còn đây bạn ? 

### ISSUE THREAD

**Issue by toniminh161200** [20021423/baitapmangP1-becodeching#9]
https://github.com/20021423/baitapmangP1-becodeching/blob/9631d56875ee65d92b9123eb6343030ebb896f74/bai1.cpp#L68
<img width="230" alt="image" src="https://user-images.githubusercontent.com/52942703/112867124-bba49200-90e4-11eb-92c0-1081d06fb447.png">

**Comment by 20021423** [comment]
mình đã sửa lên lại code, 
for (int i = 0; i < n; i++)
	{
		if (SoDoiXung(a[i]))
		{
			XoaPhanTu(a,n,i);
			i--;
		}
	}
sau khi xóa xong thì mình giảm i đi.
